version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bobace-backend-project
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bobace-frontend-project
    env_file:
      - ./frontend/.env
    environment:
      - NODE_ENV=production
      - PORT=3001
    ports:
      - "3001:3001"
    restart: unless-stopped
networks:
  webnet:
    external: true